import { expect,it } from "vitest"; import { createProviderClient } from "../../src/perplexity/client";
const response=(status:number,body="{}"):Response=>new Response(body,{status});
it("classifies auth, entitlement and provider statuses",async()=>{for(const [status,code] of [[401,"PERPLEXITY_AUTH_REQUIRED"],[402,"PERPLEXITY_ENTITLEMENT_REQUIRED"],[403,"PERPLEXITY_CHALLENGE_REQUIRED"],[429,"PERPLEXITY_RATE_LIMITED"],[500,"PERPLEXITY_UNAVAILABLE"]] as const)await expect(createProviderClient(async()=>response(status)).search("x","")).rejects.toMatchObject({code});});
it("matches the consumer ask transport and parses SSE",async()=>{let input:string|URL|Request="";let init:RequestInit|undefined;const cookie="sid=synthetic==; csrf=fixture";const fetcher=async(value:string|URL|Request,options?:RequestInit)=>{input=value;init=options;return response(200,'data: {"blocks":[{"intended_usage":"markdown","markdown_block":{"chunks":["answer"]}},{"intended_usage":"web_results","web_result_block":{"web_results":[{"name":"Source","url":"https://source.test"}]}}]}\n\ndata: {"final":true}\n\n');};const result=await createProviderClient(fetcher).search("Cloudflare Workers",cookie);expect(input).toBe("https://www.perplexity.ai/rest/sse/perplexity_ask");const headers=new Headers(init?.headers);expect(headers.get("cookie")).toBe(cookie);expect(headers.get("accept")).toBe("text/event-stream");expect(headers.get("origin")).toBe("https://www.perplexity.ai");expect(headers.get("x-app-apiversion")).toBe("2.18");const body=JSON.parse(String(init?.body)) as {query_str:string;params:{query_str:string;mode:string;search_recency_filter:null}};expect(body.query_str).toBe("Cloudflare Workers");expect(body.params).toMatchObject({query_str:"Cloudflare Workers",mode:"copilot",search_recency_filter:null});expect(result).toEqual({answer:"answer",sources:[{url:"https://source.test",title:"Source"}]});});
it("retries one transport failure before classifying the response",async()=>{let attempts=0;const result=await createProviderClient(async()=>{attempts++;if(attempts===1)throw new Error("socket reset");return response(200,'data: {"text":"answer"}\n\n');}).search("x","");expect(attempts).toBe(2);expect(result.answer).toBe("answer");});
it("rejects malformed ask SSE",async()=>{await expect(createProviderClient(async()=>response(200,"data: nope\n\n")).search("x","")).rejects.toMatchObject({code:"PERPLEXITY_PROTOCOL_ERROR"});});
it("rejects redirects and aborts caller",async()=>{await expect(createProviderClient(async(_input,_init)=>{expect((_init as RequestInit).redirect).toBe("error");return response(200,'data: {"text":"ok"}\n\n');}).search(" ","")).rejects.toMatchObject({code:"PERPLEXITY_PROTOCOL_ERROR"});const controller=new AbortController();controller.abort();await expect(createProviderClient(async()=>response(200)).search("x","",controller.signal)).rejects.toMatchObject({code:"PERPLEXITY_TIMEOUT"});});
it("aborts while waiting for streamed data",async()=>{const controller=new AbortController();const reader={read(){controller.abort();return Promise.resolve({done:true,value:undefined as never});},cancel(){return Promise.resolve();},releaseLock(){}};const responseWithReader={status:200,ok:true,body:{getReader:()=>reader}} as unknown as Response;await expect(createProviderClient(async()=>responseWithReader).search("x","",controller.signal)).rejects.toMatchObject({code:"PERPLEXITY_TIMEOUT"});});
it("bounds streamed response bodies",async()=>{const chunk=new Uint8Array(256*1024);let count=0;const stream=new ReadableStream({pull(controller){controller.enqueue(chunk);count++;if(count>=9)controller.close();}});await expect(createProviderClient(async()=>new Response(stream,{status:200})).search("x","")).rejects.toMatchObject({code:"PERPLEXITY_PROTOCOL_ERROR"});});
